# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdminDashBoard.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from GBill import G_Bill
import time
from datetime import datetime
from datetime import date
from FInsert import FIn
from Inspect import Ins
from Delete import Del
from PyQt5 import QtCore, QtGui, QtWidgets
import cx_Oracle
from Feedlis import Feed
class Admin(object):
    def openWindow_1(self):
        self.window = QtWidgets.QDialog()
        self.ui = FIn()
        self.ui.setupUi(self.window)
        self.window.show()
    def openWindow_2(self):
        self.window = QtWidgets.QDialog()
        self.ui = G_Bill()
        self.ui.setupUi(self.window)
        self.window.show()
    def openWindow_3(self):
                self.window = QtWidgets.QDialog()
                self.ui = Ins()
                self.ui.setupUi(self.window)
                self.window.show()

    def openWindow_4(self):
                self.window = QtWidgets.QDialog()
                self.ui = Del()
                self.ui.setupUi(self.window)
                self.window.show()
    def openWindow_5(self):
                self.window = QtWidgets.QDialog()
                self.ui = Feed()
                self.ui.setupUi(self.window)
                self.window.show()
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 665)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        font = QtGui.QFont()
        font.setKerning(False)
        self.widget.setFont(font)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(40, 40, 40, 40)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setStyleSheet("QFrame#frame\n"
"{\n"
"    background-color:white;\n"
"border-radius:10px;\n"
"};")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 1081, 111))
        self.groupBox.setStyleSheet("border:none;\n"
"background-color:white;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_6.setGeometry(QtCore.QRect(180, 10, 131, 20))
        self.lineEdit_6.setStyleSheet("border:none;\n"
"border-bottom: 1px solid rgb(52, 45, 113);\n"
"padding:2px;\n"
"color:rgb(52, 45, 113);")
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_7.setGeometry(QtCore.QRect(180, 40, 131, 20))
        self.lineEdit_7.setStyleSheet("border:none;\n"
"border-bottom: 1px solid rgb(52, 45, 113);\n"
"padding:2px;\n"
"color:rgb(52, 45, 113);")
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_8.setGeometry(QtCore.QRect(180, 70, 131, 20))
        self.lineEdit_8.setStyleSheet("border:none;\n"
"border-bottom: 1px solid rgb(52, 45, 113);\n"
"padding:2px;\n"
"color:rgb(52, 45, 113);")
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(510, 20, 441, 41))
        self.label.setStyleSheet("font-family:\'Montserrat\';\n"
"font-size:30px;\n"
"color:rgb(52, 45, 113);\n"
"")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(30, 20, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(52, 45, 113);")
        self.label_3.setObjectName("label_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 120, 171, 451))
        self.groupBox_2.setStyleSheet("border:none;\n"
"background-color:white;")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.InsertDataBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.InsertDataBtn.setGeometry(QtCore.QRect(10, 60, 141, 31))
        self.InsertDataBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.InsertDataBtn.setStyleSheet("QPushButton{\n"
"background-color:rgb(52, 45, 113);\n"
"color:white;\n"
"border-radius:10px;\n"
"font-size:12px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: white;\n"
"color:rgb(52, 45, 113);\n"
"border:1px solid rgb(52, 45, 113);\n"
"transform:scale(1.2);\n"
"}")
        self.InsertDataBtn.clicked.connect(lambda : self.openWindow_1())
        self.InsertDataBtn.setObjectName("InsertDataBtn")
        self.InspectDataBtn_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.InspectDataBtn_2.setGeometry(QtCore.QRect(10, 120, 141, 31))
        self.InspectDataBtn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.InspectDataBtn_2.setStyleSheet("QPushButton{\n"
"background-color:rgb(52, 45, 113);\n"
"color:white;\n"
"border-radius:10px;\n"
"font-size:12px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: white;\n"
"color:rgb(52, 45, 113);\n"
"border:1px solid rgb(52, 45, 113);\n"
"transform:scale(1.2);\n"
"}")

        self.InspectDataBtn_2.clicked.connect(lambda: self.openWindow_2())
        self.InspectDataBtn_2.setObjectName("InspectDataBtn_2")
        self.InspectDataBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.InspectDataBtn.setGeometry(QtCore.QRect(10, 180, 141, 31))
        self.InspectDataBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.InspectDataBtn.setStyleSheet("QPushButton{\n"
"background-color:rgb(52, 45, 113);\n"
"color:white;\n"
"border-radius:10px;\n"
"font-size:12px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: white;\n"
"color:rgb(52, 45, 113);\n"
"border:1px solid rgb(52, 45, 113);\n"
"transform:scale(1.2);\n"
"}")
        self.InspectDataBtn.clicked.connect(lambda :self.openWindow_3())
        self.InspectDataBtn.setObjectName("InspectDataBtn")
        self.DeleteDataBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.DeleteDataBtn.setGeometry(QtCore.QRect(10, 240, 141, 31))
        self.DeleteDataBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.DeleteDataBtn.setStyleSheet("QPushButton{\n"
"background-color:rgb(52, 45, 113);\n"
"color:white;\n"
"border-radius:10px;\n"
"font-size:12px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: white;\n"
"color:rgb(52, 45, 113);\n"
"border:1px solid rgb(52, 45, 113);\n"
"transform:scale(1.2);\n"
"}")
        self.DeleteDataBtn.clicked.connect(lambda : self.openWindow_4())
        self.DeleteDataBtn.setObjectName("DeleteDataBtn")
        #button
        self.FeedDataBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.FeedDataBtn.setGeometry(QtCore.QRect(10, 300, 141, 31))
        self.FeedDataBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FeedDataBtn.setStyleSheet("QPushButton{\n"
                                         "background-color:rgb(52, 45, 113);\n"
                                         "color:white;\n"
                                         "border-radius:10px;\n"
                                         "font-size:12px;\n"
                                         "}\n"
                                         "QPushButton:hover\n"
                                         "{\n"
                                         "background-color: white;\n"
                                         "color:rgb(52, 45, 113);\n"
                                         "border:1px solid rgb(52, 45, 113);\n"
                                         "transform:scale(1.2);\n"
                                         "}")
        self.FeedDataBtn.clicked.connect(lambda : self.openWindow_5())
        self.FeedDataBtn.setObjectName("FeedDataBtn")
        #button
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(250, 180, 291, 131))
        self.lineEdit_4.setStyleSheet("border-radius: 10px;\n"
"border: 1px solid rgb(52, 45, 113);\n"
"padding:2px;\n"
"background-color:rgb(0,128,128);")
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(580, 350, 291, 131))
        self.lineEdit_3.setStyleSheet("border-radius: 10px;\n"
"border: 1px solid rgb(52, 45, 113);\n"
"padding:2px;\n"
"background-color:rgb(0, 51, 0);")
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(340, 200, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(245,245,245);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(360, 370, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_5.setGeometry(QtCore.QRect(250, 350, 291, 131))
        self.lineEdit_5.setStyleSheet("border-radius: 10px;\n"
"border: 1px solid rgb(52, 45, 113);\n"
"padding:2px;\n"
"background-color:rgb(255, 204, 0);")
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(660, 360, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgb(245,245,245);")
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(580, 180, 291, 131))
        self.lineEdit.setStyleSheet("border-radius: 10px;\n"
"border: 1px solid rgb(52, 45, 113);\n"
"padding:2px;\n"
"color:rgb(52, 45, 113);\n"
"background-color:rgb(250, 160, 160);")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(690, 200, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgb(245,245,245);")
        self.label_7.setObjectName("label_7")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(900, 180, 151, 301))
        self.lineEdit_2.setStyleSheet("border-radius: 10px;\n"
"border: 1px solid rgb(52, 45, 113);\n"
"padding:2px;\n"
"background-color:rgb(0, 128, 128);")
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(950, 210, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(366, 240, 161, 51))
        self.label_2.setStyleSheet("color:rgb(245,245,245);\n"
"background-color:rgb(0,128,128);\n"
"font-size:37px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(356, 410, 161, 49))
        self.label_9.setStyleSheet("color:black;\n"
"background-color:rgb(255,204,0);\n"
"padding:10px;\n"
"font-size:37px;")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(676, 240, 181, 51))
        self.label_10.setStyleSheet("\n"
"padding:10px;\n"
"color:white;\n"
"background-color:rgb(250, 160, 160);\n"
"font-size:37px;")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(676, 400, 171, 51))
        self.label_11.setStyleSheet("padding:10px;\n"
"color:white;\n"
"font-size:37px;")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(956, 262, 81, 121))
        self.label_12.setStyleSheet("padding:10px;\n"
"color:black;\n"
"font-size:37px;")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(470, 520, 321, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.lineEdit_4.raise_()
        self.lineEdit_3.raise_()
        self.label_4.raise_()
        self.lineEdit_5.raise_()
        self.label_6.raise_()
        self.lineEdit.raise_()
        self.label_7.raise_()
        self.lineEdit_2.raise_()
        self.label_5.raise_()
        self.label_8.raise_()
        self.label_2.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        now = datetime.now()
        current_time = str(now.strftime("%H:%M:%S"))
        today = str(date.today())
        self.lineEdit_7.setText(today)
        self.lineEdit_8.setText(current_time)
        try:
                with cx_Oracle.connect('system/Oracle123') as co:
                        cur = co.cursor()
                        sql = """SELECT COUNT(*) FROM PERSON"""
                        x = cur.execute(sql)
                        l= []
                        for item in x:
                                l += item
                        for y in l:
                                strin = str(y)
                        self.label_2.setText(strin)
                        sql = """SELECT COUNT(*) FROM EMPL_DBS"""
                        x = cur.execute(sql)
                        l = []
                        for item in x:
                                l += item
                        for y in l:
                                strin = str(y)
                        self.label_10.setText(strin)
                        sql = """SELECT COUNT(*) FROM B_X"""
                        x = cur.execute(sql)
                        l = []
                        for item in x:
                                l += item
                        for y in l:
                                strin = str(y)
                        self.label_9.setText(strin)
                        sql = """SELECT COUNT(*) FROM Feed_bac"""
                        x = cur.execute(sql)
                        l = []
                        for item in x:
                                l += item
                        for y in l:
                                strin = str(y)
                        self.label_11.setText(strin)
                        sql = """SELECT COUNT(*) FROM ALERT_SYS"""
                        x = cur.execute(sql)
                        l = []
                        for item in x:
                                l += item
                        for y in l:
                                strin = str(y)
                        self.label_12.setText(strin)
                        co.commit()

        except Exception as e:
                print("Error: ", str(e))
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lineEdit_6.setText(_translate("Dialog", "Admin"))
        self.label.setText(_translate("Dialog", "Welcome To Admin Dashboard"))
        self.label_3.setText(_translate("Dialog", "ⓔ IESCO"))
        self.InsertDataBtn.setText(_translate("Dialog", "Insert/Update Data"))
        self.InspectDataBtn_2.setText(_translate("Dialog", "Generate Bill"))
        self.InspectDataBtn.setText(_translate("Dialog", "Inspect Data"))
        self.DeleteDataBtn.setText(_translate("Dialog", "Delete Data"))
        self.FeedDataBtn.setText(_translate("Dialog", "View FeedBack List"))
        self.label_4.setText(_translate("Dialog", "Total Customer"))
        self.label_5.setText(_translate("Dialog", "Total Bills"))
        self.label_6.setText(_translate("Dialog", "Total Feedbacks"))
        self.label_7.setText(_translate("Dialog", "Employees"))
        self.label_8.setText(_translate("Dialog", "Alerts"))
        self.label_13.setText(_translate("Dialog", "© Copyright 2023 Made with By IESCO"))

    def setup(self):
        try:
            with cx_Oracle.connect('system/Oracle123') as co:
                    cur = co.cursor()
                    sql = """SELECT COUNT(*) FROM PERSON;"""
                    x=cur.execute(sql)
                    print(x)
                    co.commit()

        except Exception as e:
                print("Error: ", str(e))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Admin()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
