# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BillReceipt.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class B_R(object):
    def window3(self):
        exit()
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1086, 554)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bgwidget = QtWidgets.QWidget(Dialog)
        self.bgwidget.setStyleSheet("QWidget#bgwidget\n"
"{\n"
"background-image: url(../images.qrc/home-hero-left.webp);\n"
"background-repeat:no-repeat;\n"
"};\n"
"")
        self.bgwidget.setObjectName("bgwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.bgwidget)
        self.verticalLayout_2.setContentsMargins(40, 40, 40, 40)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.bgwidget)
        self.groupBox.setStyleSheet("QGroupBox#groupBox\n"
"{\n"
"    border-radius:10px;\n"
"background-color: rgb(255, 255, 255);\n"
"};\n"
"\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(460, 10, 471, 81))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("font: 80 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 127);")
        self.label_7.setObjectName("label_7")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(-80, 10, 581, 411))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../images.qrc/abstract-blue-fluid-background-vector-260nw-2175996105.webp"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setGeometry(QtCore.QRect(410, 70, 561, 341))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Receipt_SaveToGallery = QtWidgets.QPushButton(self.frame)
        self.Receipt_SaveToGallery.setGeometry(QtCore.QRect(200, 270, 181, 41))
        self.Receipt_SaveToGallery.setStyleSheet("QPushButton{\n"
"background-color:rgb(30,144,255);\n"
"color:white;\n"
"border-radius:20px;\n"
"font-size:20px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"\n"
"background-color: white;\n"
"color:rgb(30,144,255);\n"
"border:1px solid rgb(30,144,255);\n"
"transform:scale(1.2);\n"
"}")
        self.Receipt_SaveToGallery.clicked.connect(lambda :self.window3())
        self.Receipt_SaveToGallery.setObjectName("Receipt_SaveToGallery")
        self.Receipt_Status = QtWidgets.QLineEdit(self.frame)
        self.Receipt_Status.setGeometry(QtCore.QRect(190, 170, 311, 31))
        self.Receipt_Status.setStyleSheet("border:none;")
        self.Receipt_Status.setReadOnly(True)
        self.Receipt_Status.setObjectName("Receipt_Status")
        self.ReceiptRefNo = QtWidgets.QLineEdit(self.frame)
        self.ReceiptRefNo.setGeometry(QtCore.QRect(190, 90, 311, 31))
        self.ReceiptRefNo.setStyleSheet("border:none;")
        self.ReceiptRefNo.setReadOnly(True)
        self.ReceiptRefNo.setObjectName("ReceiptRefNo")
        self.label_33 = QtWidgets.QLabel(self.frame)
        self.label_33.setGeometry(QtCore.QRect(60, 220, 121, 16))
        self.label_33.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.label_33.setObjectName("label_33")
        self.Receipt_Date = QtWidgets.QLineEdit(self.frame)
        self.Receipt_Date.setGeometry(QtCore.QRect(190, 210, 311, 31))
        self.Receipt_Date.setStyleSheet("border:none;")
        self.Receipt_Date.setReadOnly(True)
        self.Receipt_Date.setObjectName("Receipt_Date")
        self.label_29 = QtWidgets.QLabel(self.frame)
        self.label_29.setGeometry(QtCore.QRect(60, 180, 121, 16))
        self.label_29.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.frame)
        self.label_30.setGeometry(QtCore.QRect(60, 100, 121, 16))
        self.label_30.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.label_30.setObjectName("label_30")
        self.label_32 = QtWidgets.QLabel(self.frame)
        self.label_32.setGeometry(QtCore.QRect(60, 60, 121, 16))
        self.label_32.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.label_32.setObjectName("label_32")
        self.Receipt_BillID = QtWidgets.QLineEdit(self.frame)
        self.Receipt_BillID.setGeometry(QtCore.QRect(190, 50, 311, 31))
        self.Receipt_BillID.setStyleSheet("border:none;\n"
"")
        self.Receipt_BillID.setReadOnly(True)
        self.Receipt_BillID.setObjectName("Receipt_BillID")
        self.ReceiptMeterNo = QtWidgets.QLineEdit(self.frame)
        self.ReceiptMeterNo.setGeometry(QtCore.QRect(190, 130, 311, 31))
        self.ReceiptMeterNo.setStyleSheet("border:none;")
        self.ReceiptMeterNo.setText("")
        self.ReceiptMeterNo.setReadOnly(True)
        self.ReceiptMeterNo.setObjectName("ReceiptMeterNo")
        self.label_31 = QtWidgets.QLabel(self.frame)
        self.label_31.setGeometry(QtCore.QRect(60, 140, 121, 16))
        self.label_31.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.label_31.setObjectName("label_31")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(50, 20, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(30,144,255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.groupBox)
        self.verticalLayout.addWidget(self.bgwidget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_7.setText(_translate("Dialog", "Thanks! Bill Paid Successfully"))
        self.Receipt_SaveToGallery.setText(_translate("Dialog", "Exit"))
        self.label_33.setText(_translate("Dialog", "Receipt Date"))
        self.label_29.setText(_translate("Dialog", "Status"))
        self.label_30.setText(_translate("Dialog", "Reference No"))
        self.label_32.setText(_translate("Dialog", "Bill ID"))
        self.label_31.setText(_translate("Dialog", "Meter No"))
        self.label_2.setText(_translate("Dialog", "ⓔ IESCO"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = B_R()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
