# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Feedlis.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from FShow import Show
import cx_Oracle
class Feed(object):
    def openWindow(self):
        exit()
    def openWindow_1(self):
        self.window = QtWidgets.QDialog()
        self.ui = Show()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 500)
        font = QtGui.QFont()
        font.setPointSize(15)
        Dialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bgwidget = QtWidgets.QWidget(Dialog)
        self.bgwidget.setStyleSheet("QWidget#bgwidget{\n"
"    background-image:  url(../images.qrc/vecteezy_hexagon-abstract-modern-background-with-overlapping-triangle_5909540.jpg);\n"
"    \n"
"};\n"
"")
        self.bgwidget.setObjectName("bgwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.bgwidget)
        self.verticalLayout_2.setContentsMargins(40, 40, 40, 40)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.bgwidget)
        self.groupBox.setStyleSheet("QGroupBox#groupBox\n"
"{\n"
"background-color:white;\n"
"border-radius:10px;\n"
"};")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(510, 120, 441, 391))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../garbage/FeedbackImage.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.SubmitFdbckBtn_2 = QtWidgets.QPushButton(self.groupBox)
        self.SubmitFdbckBtn_2.setGeometry(QtCore.QRect(80, 280, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.SubmitFdbckBtn_2.setFont(font)
        self.SubmitFdbckBtn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SubmitFdbckBtn_2.setStyleSheet("QPushButton{\n"
"background-color:rgb(52, 45, 113);\n"
"color:white;\n"
"border-radius:10px;\n"
"font-size:19px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: white;\n"
"color:rgb(52, 45, 113);\n"
"border:1px solid rgb(52, 45, 113);\n"
"transform:scale(1.2);\n"
"}")
        self.SubmitFdbckBtn_2.clicked.connect(lambda :self.openWindow_1())
        self.SubmitFdbckBtn_2.setObjectName("SubmitFdbckBtn_2")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setGeometry(QtCore.QRect(30, 70, 341, 192))
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setRowCount(15)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.verticalHeader().setMinimumSectionSize(25)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(52, 45, 113);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(290, 10, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(52, 45, 113);")
        self.label_3.setObjectName("label_3")
        self.SubmitFdbckBtn_3 = QtWidgets.QPushButton(self.groupBox)
        self.SubmitFdbckBtn_3.setGeometry(QtCore.QRect(80, 330, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.SubmitFdbckBtn_3.setFont(font)
        self.SubmitFdbckBtn_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SubmitFdbckBtn_3.setStyleSheet("QPushButton{\n"
"background-color:rgb(52, 45, 113);\n"
"color:white;\n"
"border-radius:10px;\n"
"font-size:19px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: white;\n"
"color:rgb(52, 45, 113);\n"
"border:1px solid rgb(52, 45, 113);\n"
"transform:scale(1.2);\n"
"}")
        self.SubmitFdbckBtn_3.clicked.connect(lambda :self.openWindow())
        self.SubmitFdbckBtn_3.setObjectName("SubmitFdbckBtn_3")
        self.verticalLayout_2.addWidget(self.groupBox)
        self.verticalLayout.addWidget(self.bgwidget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.SubmitFdbckBtn_2.setText(_translate("Dialog", "View Feedback"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Department"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Category"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Reference No"))
        self.label_2.setText(_translate("Dialog", "FeedBack List"))
        self.label_3.setText(_translate("Dialog", "ⓔ IESCO"))
        self.SubmitFdbckBtn_3.setText(_translate("Dialog", "Exit"))
        try:
            with cx_Oracle.connect('system/Oracle123') as co:
                cur = co.cursor()
                quey = """SELECT * FROM Feed"""
                result = cur.execute(quey)
                self.tableWidget.setRowCount(0)
                for rowNo, row_data in enumerate(result):
                    self.tableWidget.insertRow(rowNo)
                    for col_no, col_data in enumerate(row_data):
                        self.tableWidget.setItem(rowNo, col_no, QtWidgets.QTableWidgetItem(str(col_data)))
        except Exception as e:
            print("Error: ", str(e))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Feed()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
